name: Feature request
description: Add feature proposition
title: "[Bug]: "
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: dropdown
    id: plugin
    attributes:
      label: Plugin
      options:
        - QML Editor
        - Qt Style Sheets Editor
        - Qt Style Sheets Highlighter
        - New plugin
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      placeholder: "Please describe feature"
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: Example
      placeholder: "Please provide link for similar features in other plugins/editor"
    validations:
      required: false